// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GSS.Controllers
{
    public partial class AdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UserDetailsView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserDetailsView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ManagePages()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManagePages);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeletePage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ContentView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContentView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddGallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddGallery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateBannerImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateBannerImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteEventImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEventImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewsEvents()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsEvents);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteNewsEvents()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteNewsEvents);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewsEventsDetailView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsEventsDetailView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ContactUs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactUs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteContactus()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteContactus);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ContactusDetailView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactusDetailView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddHukamnama()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddHukamnama);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteHukamnama()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteHukamnama);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewHukamnama()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewHukamnama);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddVideo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVideo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteVideo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVideo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ManageSubscription()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageSubscription);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteSubscription()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSubscription);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddEventGallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEventGallery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteEventGallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEventGallery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteEventGalleryImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEventGalleryImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetByCommitteeId()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetByCommitteeId);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string DashBoard = "DashBoard";
            public readonly string CreateUser = "CreateUser";
            public readonly string Delete = "Delete";
            public readonly string UserDetailsView = "UserDetailsView";
            public readonly string ManagePages = "ManagePages";
            public readonly string DeletePage = "DeletePage";
            public readonly string ViewPagesGrid = "ViewPagesGrid";
            public readonly string ContentView = "ContentView";
            public readonly string AddGallery = "AddGallery";
            public readonly string GalleryView = "GalleryView";
            public readonly string DeleteImage = "DeleteImage";
            public readonly string UpdateBannerImage = "UpdateBannerImage";
            public readonly string DeleteEventImage = "DeleteEventImage";
            public readonly string NewsEvents = "NewsEvents";
            public readonly string DeleteNewsEvents = "DeleteNewsEvents";
            public readonly string NewsEventsDetailView = "NewsEventsDetailView";
            public readonly string NewsEventsView = "NewsEventsView";
            public readonly string ContactUs = "ContactUs";
            public readonly string DeleteContactus = "DeleteContactus";
            public readonly string ContactusView = "ContactusView";
            public readonly string ContactusDetailView = "ContactusDetailView";
            public readonly string AddHukamnama = "AddHukamnama";
            public readonly string GetHukamnamasResult = "GetHukamnamasResult";
            public readonly string DeleteHukamnama = "DeleteHukamnama";
            public readonly string ViewHukamnama = "ViewHukamnama";
            public readonly string CommitteMembers = "CommitteMembers";
            public readonly string CreateMember = "CreateMember";
            public readonly string DeleteMember = "DeleteMember";
            public readonly string AddVideo = "AddVideo";
            public readonly string VideoGalleryListView = "VideoGalleryListView";
            public readonly string DeleteVideo = "DeleteVideo";
            public readonly string SubscribedMembers = "SubscribedMembers";
            public readonly string ManageSubscription = "ManageSubscription";
            public readonly string DeleteSubscription = "DeleteSubscription";
            public readonly string AddEventGallery = "AddEventGallery";
            public readonly string DeleteEventGallery = "DeleteEventGallery";
            public readonly string EventGalleryList = "EventGalleryList";
            public readonly string DeleteEventGalleryImage = "DeleteEventGalleryImage";
            public readonly string GetByCommitteeId = "GetByCommitteeId";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string DashBoard = "DashBoard";
            public const string CreateUser = "CreateUser";
            public const string Delete = "Delete";
            public const string UserDetailsView = "UserDetailsView";
            public const string ManagePages = "ManagePages";
            public const string DeletePage = "DeletePage";
            public const string ViewPagesGrid = "ViewPagesGrid";
            public const string ContentView = "ContentView";
            public const string AddGallery = "AddGallery";
            public const string GalleryView = "GalleryView";
            public const string DeleteImage = "DeleteImage";
            public const string UpdateBannerImage = "UpdateBannerImage";
            public const string DeleteEventImage = "DeleteEventImage";
            public const string NewsEvents = "NewsEvents";
            public const string DeleteNewsEvents = "DeleteNewsEvents";
            public const string NewsEventsDetailView = "NewsEventsDetailView";
            public const string NewsEventsView = "NewsEventsView";
            public const string ContactUs = "ContactUs";
            public const string DeleteContactus = "DeleteContactus";
            public const string ContactusView = "ContactusView";
            public const string ContactusDetailView = "ContactusDetailView";
            public const string AddHukamnama = "AddHukamnama";
            public const string GetHukamnamasResult = "GetHukamnamasResult";
            public const string DeleteHukamnama = "DeleteHukamnama";
            public const string ViewHukamnama = "ViewHukamnama";
            public const string CommitteMembers = "CommitteMembers";
            public const string CreateMember = "CreateMember";
            public const string DeleteMember = "DeleteMember";
            public const string AddVideo = "AddVideo";
            public const string VideoGalleryListView = "VideoGalleryListView";
            public const string DeleteVideo = "DeleteVideo";
            public const string SubscribedMembers = "SubscribedMembers";
            public const string ManageSubscription = "ManageSubscription";
            public const string DeleteSubscription = "DeleteSubscription";
            public const string AddEventGallery = "AddEventGallery";
            public const string DeleteEventGallery = "DeleteEventGallery";
            public const string EventGalleryList = "EventGalleryList";
            public const string DeleteEventGalleryImage = "DeleteEventGalleryImage";
            public const string GetByCommitteeId = "GetByCommitteeId";
        }


        static readonly ActionParamsClass_CreateUser s_params_CreateUser = new ActionParamsClass_CreateUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateUser CreateUserParams { get { return s_params_CreateUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateUser
        {
            public readonly string id = "id";
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UserDetailsView s_params_UserDetailsView = new ActionParamsClass_UserDetailsView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserDetailsView UserDetailsViewParams { get { return s_params_UserDetailsView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserDetailsView
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ManagePages s_params_ManagePages = new ActionParamsClass_ManagePages();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManagePages ManagePagesParams { get { return s_params_ManagePages; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManagePages
        {
            public readonly string id = "id";
            public readonly string pagedetails = "pagedetails";
            public readonly string myArea1 = "myArea1";
            public readonly string form = "form";
        }
        static readonly ActionParamsClass_DeletePage s_params_DeletePage = new ActionParamsClass_DeletePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePage DeletePageParams { get { return s_params_DeletePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ContentView s_params_ContentView = new ActionParamsClass_ContentView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ContentView ContentViewParams { get { return s_params_ContentView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ContentView
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddGallery s_params_AddGallery = new ActionParamsClass_AddGallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddGallery AddGalleryParams { get { return s_params_AddGallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddGallery
        {
            public readonly string id = "id";
            public readonly string gallery = "gallery";
        }
        static readonly ActionParamsClass_DeleteImage s_params_DeleteImage = new ActionParamsClass_DeleteImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteImage DeleteImageParams { get { return s_params_DeleteImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteImage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateBannerImage s_params_UpdateBannerImage = new ActionParamsClass_UpdateBannerImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateBannerImage UpdateBannerImageParams { get { return s_params_UpdateBannerImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateBannerImage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteEventImage s_params_DeleteEventImage = new ActionParamsClass_DeleteEventImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteEventImage DeleteEventImageParams { get { return s_params_DeleteEventImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteEventImage
        {
            public readonly string id = "id";
            public readonly string eventId = "eventId";
        }
        static readonly ActionParamsClass_NewsEvents s_params_NewsEvents = new ActionParamsClass_NewsEvents();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsEvents NewsEventsParams { get { return s_params_NewsEvents; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsEvents
        {
            public readonly string Id = "Id";
            public readonly string model = "model";
            public readonly string file1 = "file1";
            public readonly string myArea1 = "myArea1";
            public readonly string form = "form";
        }
        static readonly ActionParamsClass_DeleteNewsEvents s_params_DeleteNewsEvents = new ActionParamsClass_DeleteNewsEvents();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteNewsEvents DeleteNewsEventsParams { get { return s_params_DeleteNewsEvents; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteNewsEvents
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_NewsEventsDetailView s_params_NewsEventsDetailView = new ActionParamsClass_NewsEventsDetailView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsEventsDetailView NewsEventsDetailViewParams { get { return s_params_NewsEventsDetailView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsEventsDetailView
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ContactUs s_params_ContactUs = new ActionParamsClass_ContactUs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ContactUs ContactUsParams { get { return s_params_ContactUs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ContactUs
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteContactus s_params_DeleteContactus = new ActionParamsClass_DeleteContactus();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteContactus DeleteContactusParams { get { return s_params_DeleteContactus; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteContactus
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ContactusDetailView s_params_ContactusDetailView = new ActionParamsClass_ContactusDetailView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ContactusDetailView ContactusDetailViewParams { get { return s_params_ContactusDetailView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ContactusDetailView
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddHukamnama s_params_AddHukamnama = new ActionParamsClass_AddHukamnama();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddHukamnama AddHukamnamaParams { get { return s_params_AddHukamnama; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddHukamnama
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteHukamnama s_params_DeleteHukamnama = new ActionParamsClass_DeleteHukamnama();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteHukamnama DeleteHukamnamaParams { get { return s_params_DeleteHukamnama; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteHukamnama
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ViewHukamnama s_params_ViewHukamnama = new ActionParamsClass_ViewHukamnama();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewHukamnama ViewHukamnamaParams { get { return s_params_ViewHukamnama; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewHukamnama
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CreateMember s_params_CreateMember = new ActionParamsClass_CreateMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateMember CreateMemberParams { get { return s_params_CreateMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateMember
        {
            public readonly string id = "id";
            public readonly string committeMember = "committeMember";
        }
        static readonly ActionParamsClass_DeleteMember s_params_DeleteMember = new ActionParamsClass_DeleteMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteMember DeleteMemberParams { get { return s_params_DeleteMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteMember
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddVideo s_params_AddVideo = new ActionParamsClass_AddVideo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddVideo AddVideoParams { get { return s_params_AddVideo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddVideo
        {
            public readonly string id = "id";
            public readonly string gallery = "gallery";
        }
        static readonly ActionParamsClass_DeleteVideo s_params_DeleteVideo = new ActionParamsClass_DeleteVideo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteVideo DeleteVideoParams { get { return s_params_DeleteVideo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteVideo
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ManageSubscription s_params_ManageSubscription = new ActionParamsClass_ManageSubscription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageSubscription ManageSubscriptionParams { get { return s_params_ManageSubscription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageSubscription
        {
            public readonly string id = "id";
            public readonly string subscription = "subscription";
        }
        static readonly ActionParamsClass_DeleteSubscription s_params_DeleteSubscription = new ActionParamsClass_DeleteSubscription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSubscription DeleteSubscriptionParams { get { return s_params_DeleteSubscription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSubscription
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddEventGallery s_params_AddEventGallery = new ActionParamsClass_AddEventGallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddEventGallery AddEventGalleryParams { get { return s_params_AddEventGallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddEventGallery
        {
            public readonly string id = "id";
            public readonly string model = "model";
            public readonly string file1 = "file1";
        }
        static readonly ActionParamsClass_DeleteEventGallery s_params_DeleteEventGallery = new ActionParamsClass_DeleteEventGallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteEventGallery DeleteEventGalleryParams { get { return s_params_DeleteEventGallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteEventGallery
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteEventGalleryImage s_params_DeleteEventGalleryImage = new ActionParamsClass_DeleteEventGalleryImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteEventGalleryImage DeleteEventGalleryImageParams { get { return s_params_DeleteEventGalleryImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteEventGalleryImage
        {
            public readonly string id = "id";
            public readonly string eventId = "eventId";
        }
        static readonly ActionParamsClass_GetByCommitteeId s_params_GetByCommitteeId = new ActionParamsClass_GetByCommitteeId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetByCommitteeId GetByCommitteeIdParams { get { return s_params_GetByCommitteeId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetByCommitteeId
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminController : GSS.Controllers.AdminController
    {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        [NonAction]
        partial void DashBoardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DashBoard()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DashBoard);
            DashBoardOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateUser(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CreateUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.UserModel user);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateUser(GSS.Models.Models.UserModel user)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            CreateUserOverride(callInfo, user);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UserDetailsViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserDetailsView(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserDetailsView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UserDetailsViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ManagePagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManagePages(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManagePages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ManagePagesOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ManagePagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.PagesModel pagedetails, string myArea1, System.Web.Mvc.FormCollection form);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManagePages(GSS.Models.Models.PagesModel pagedetails, string myArea1, System.Web.Mvc.FormCollection form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManagePages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pagedetails", pagedetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "myArea1", myArea1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            ManagePagesOverride(callInfo, pagedetails, myArea1, form);
            return callInfo;
        }

        [NonAction]
        partial void DeletePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeletePage(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeletePageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ViewPagesGridOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewPagesGrid()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewPagesGrid);
            ViewPagesGridOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContentViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContentView(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContentView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ContentViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddGallery(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddGalleryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.GalleryModel gallery);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddGallery(GSS.Models.Models.GalleryModel gallery)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gallery", gallery);
            AddGalleryOverride(callInfo, gallery);
            return callInfo;
        }

        [NonAction]
        partial void GalleryViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GalleryView()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GalleryView);
            GalleryViewOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteImage(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteImageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateBannerImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateBannerImage(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateBannerImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UpdateBannerImageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteEventImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string eventId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteEventImage(string id, string eventId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEventImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eventId", eventId);
            DeleteEventImageOverride(callInfo, id, eventId);
            return callInfo;
        }

        [NonAction]
        partial void NewsEventsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsEvents(string Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsEvents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            NewsEventsOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void NewsEventsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.NewsEventsModel model, System.Web.HttpPostedFileBase[] file1, string myArea1, System.Web.Mvc.FormCollection form);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsEvents(GSS.Models.Models.NewsEventsModel model, System.Web.HttpPostedFileBase[] file1, string myArea1, System.Web.Mvc.FormCollection form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsEvents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file1", file1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "myArea1", myArea1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            NewsEventsOverride(callInfo, model, file1, myArea1, form);
            return callInfo;
        }

        [NonAction]
        partial void DeleteNewsEventsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteNewsEvents(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteNewsEvents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteNewsEventsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void NewsEventsDetailViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsEventsDetailView(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsEventsDetailView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NewsEventsDetailViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void NewsEventsViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsEventsView()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsEventsView);
            NewsEventsViewOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContactUsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContactUs(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactUs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ContactUsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ContactUsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.ContactUsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContactUs(GSS.Models.Models.ContactUsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactUs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ContactUsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteContactusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteContactus(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteContactus);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteContactusOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ContactusViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContactusView()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactusView);
            ContactusViewOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContactusDetailViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContactusDetailView(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactusDetailView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ContactusDetailViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddHukamnamaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddHukamnama(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddHukamnama);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddHukamnamaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddHukamnamaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.HukamnamaModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddHukamnama(GSS.Models.Models.HukamnamaModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddHukamnama);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddHukamnamaOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetHukamnamasResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetHukamnamasResult()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetHukamnamasResult);
            GetHukamnamasResultOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteHukamnamaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteHukamnama(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteHukamnama);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteHukamnamaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ViewHukamnamaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewHukamnama(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewHukamnama);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewHukamnamaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CommitteMembersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CommitteMembers()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CommitteMembers);
            CommitteMembersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateMember(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CreateMemberOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.CommitteMemberModel committeMember);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateMember(GSS.Models.Models.CommitteMemberModel committeMember)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "committeMember", committeMember);
            CreateMemberOverride(callInfo, committeMember);
            return callInfo;
        }

        [NonAction]
        partial void DeleteMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteMember(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteMemberOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVideoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVideo(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVideo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddVideoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVideoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.VideoGalleryModel gallery);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVideo(GSS.Models.Models.VideoGalleryModel gallery)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVideo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gallery", gallery);
            AddVideoOverride(callInfo, gallery);
            return callInfo;
        }

        [NonAction]
        partial void VideoGalleryListViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult VideoGalleryListView()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VideoGalleryListView);
            VideoGalleryListViewOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteVideoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteVideo(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVideo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteVideoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SubscribedMembersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SubscribedMembers()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubscribedMembers);
            SubscribedMembersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ManageSubscriptionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManageSubscription(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageSubscription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ManageSubscriptionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ManageSubscriptionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.SubscriptionModel subscription);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManageSubscription(GSS.Models.Models.SubscriptionModel subscription)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageSubscription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "subscription", subscription);
            ManageSubscriptionOverride(callInfo, subscription);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSubscriptionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteSubscription(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSubscription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteSubscriptionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddEventGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEventGallery(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEventGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddEventGalleryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddEventGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GSS.Models.Models.EventGalleryModel model, System.Web.HttpPostedFileBase[] file1);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEventGallery(GSS.Models.Models.EventGalleryModel model, System.Web.HttpPostedFileBase[] file1)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEventGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file1", file1);
            AddEventGalleryOverride(callInfo, model, file1);
            return callInfo;
        }

        [NonAction]
        partial void DeleteEventGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteEventGallery(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEventGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteEventGalleryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EventGalleryListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EventGalleryList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EventGalleryList);
            EventGalleryListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteEventGalleryImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string eventId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteEventGalleryImage(string id, string eventId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEventGalleryImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eventId", eventId);
            DeleteEventGalleryImageOverride(callInfo, id, eventId);
            return callInfo;
        }

        [NonAction]
        partial void GetByCommitteeIdOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetByCommitteeId(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetByCommitteeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetByCommitteeIdOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
