//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventImage
    {
        public long Id { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public long EventGalleryId { get; set; }
    
        public virtual EventGallery EventGallery { get; set; }
    }
}
