//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSS.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSSEntities : DbContext
    {
        public GSSEntities()
            : base("name=GSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommitteeMember> CommitteeMembers { get; set; }
        public virtual DbSet<Committee> Committees { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<EventGallery> EventGalleries { get; set; }
        public virtual DbSet<EventImage> EventImages { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Hukamnama> Hukamnamas { get; set; }
        public virtual DbSet<LiveStream> LiveStreams { get; set; }
        public virtual DbSet<MembersToCommittee> MembersToCommittees { get; set; }
        public virtual DbSet<NewsEvent> NewsEvents { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VideoGallery> VideoGalleries { get; set; }
    }
}
