//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersToCommittee
    {
        public int Id { get; set; }
        public long MemberId { get; set; }
        public long CommitteeId { get; set; }
    
        public virtual CommitteeMember CommitteeMember { get; set; }
        public virtual Committee Committee { get; set; }
    }
}
